### PR TITLE
Adding simple test harness, composer.json for phpunit

### PR DESCRIPTION
**Pull request by astorm**
This pull requests adds a simple test harness.  

The composer.json and composer.lock will allow third party developers to install the needed PHPUnit executable by running 

    composer.phar install

This is pretty standard in PHP projects these days.  Once composer's done its thing, users can run tests with 

    vendor/bin/phpunit tests

Once the multi-file work is don we'll probably need to change the `setUp` method in the base class, depending on what happens there.

### CODE REVIEW

**Comment by unirgy** [comment]
I'd prefer to move out the class to a separate file, make all relevan methods as public, and update _readFile/_writeFile to accept mock data. what do you think?

**Comment by astorm** [comment]
@unirgy Re: the mocks, that sounds like a decent..  Re: moving "the class to a separate file", I'm not sure what you mean by that.

**Comment by unirgy** [comment]
Please see my latest commit - basically now you have a separate class without bootstrap code, and all methods are public for ease of testing.

**Comment by astorm** [comment]
Got it -- just fixed the pull request do it doesn't conflict.  Do we need anything else here for this initial test framework commit?

**Comment by unirgy** [comment]
I've added `setTestMode()`, `addTestInputFile($contents)`, `getTestOutputFile() == $contents` to mock file operations. Not sure what to do with copy, delete and glob operations.

An example of a test would be:

```php
public function testConvertConfigAcl() 
{
    $convert = new ConvertM1M2('source', 'm1', 'm2');

    $convert->setTestMode();
    $convert->addTestInputFile($configXmlContents);
    $convert->addTestInputFile($adminhtmlXmlContents);

    $convert->convertConfigAcl();

    $resultContents = $convert->getTestOutputFile();

    $this->assertContains($resultContents, '...');
}
```

What do you think?

**Pull request merged**
